version: '3.1'

services:
  db:
    container_name: postgres-container
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: EventBooking
    ports:
      - "5434:5434"
    expose:
      - "5434"
    volumes:
      - ./postgres-dataz:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build: .
    container_name: backend-container
    restart: always
    ports:
      - "8084:9000"
    expose:
      - "9000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5434/EventBooking
      SPRING_DATASOURCE_USERNAME:
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    image: event-management-system-backend
